// Code generated by go2zig. DO NOT EDIT.
//go:build ((windows || linux) && (amd64 || arm64)) || (darwin && arm64)

package main

import (
	"fmt"
	"path/filepath"
	"runtime"
	"sync"
	"unsafe"

	"go2zig/asmcall"
	"go2zig/dynlib"
	"io"
	"os"
)

type Go2ZigClient struct {
	rt *_go2zigRuntime
}

func NewGo2ZigClient(path string) *Go2ZigClient {
	return &Go2ZigClient{rt: &_go2zigRuntime{path: path}}
}

var Default = NewGo2ZigClient("")

type _go2zigRuntime struct {
	path           string
	once           sync.Once
	lib            *dynlib.Library
	freeBuf        uintptr
	procCopyStream uintptr
	err            error
}

func (rt *_go2zigRuntime) Load() error {
	rt.once.Do(func() {
		path := rt.path
		if path == "" {
			path = _go2zigDefaultLibraryPath()
		}
		lib, err := dynlib.Load(path)
		if err != nil {
			rt.err = fmt.Errorf("go2zig: load %s: %w", path, err)
			return
		}
		rt.lib = lib
		if rt.freeBuf, err = lib.Lookup("go2zig_free_buf"); err != nil {
			rt.err = fmt.Errorf("go2zig: lookup go2zig_free_buf: %w", err)
			return
		}
		if rt.procCopyStream, err = lib.Lookup("go2zig_call_copy_stream"); err != nil {
			rt.err = fmt.Errorf("go2zig: lookup go2zig_call_copy_stream: %w", err)
			return
		}
	})
	return rt.err
}

func (rt *_go2zigRuntime) free(ptr unsafe.Pointer, len uintptr) {
	if ptr == nil || len == 0 {
		return
	}
	if err := rt.Load(); err != nil {
		panic(err)
	}
	asmcall.CallFuncG0P2(unsafe.Pointer(rt.freeBuf), ptr, unsafe.Pointer(len))
}

func (rt *_go2zigRuntime) call(proc uintptr, frame unsafe.Pointer) {
	if err := rt.Load(); err != nil {
		panic(err)
	}
	asmcall.CallFuncG0P1(unsafe.Pointer(proc), frame)
}

type _go2zigStreamState struct {
	file      *os.File
	owned     io.Closer
	upstream  io.Closer
	done      chan error
	closeOnce sync.Once
	waitOnce  sync.Once
	err       error
}

func (s *_go2zigStreamState) handle() uintptr {
	if s == nil || s.file == nil {
		return 0
	}
	return s.file.Fd()
}

func (s *_go2zigStreamState) wait() error {
	if s == nil || s.done == nil {
		return nil
	}
	s.waitOnce.Do(func() {
		s.err = <-s.done
	})
	return s.err
}

func (s *_go2zigStreamState) closeOwned() error {
	if s == nil {
		return nil
	}
	var err error
	s.closeOnce.Do(func() {
		if s.owned != nil {
			err = s.owned.Close()
		}
	})
	return err
}

func (s *_go2zigStreamState) close(ignoreErr bool) error {
	if s == nil {
		return nil
	}
	closeErr := s.closeOwned()
	if s.upstream != nil && closeErr != nil {
		closeErr = nil
	}
	if s.done == nil {
		if ignoreErr {
			return nil
		}
		return closeErr
	}
	if ignoreErr {
		go func() { _ = s.wait() }()
		return nil
	}
	err := s.wait()
	if closeErr != nil {
		return closeErr
	}
	return err
}

type GoReader struct {
	state *_go2zigStreamState
}

type GoWriter struct {
	state *_go2zigStreamState
}

func NewGoReadCloser(reader io.ReadCloser) (GoReader, error) {
	return newGoReader(reader, reader)
}

func NewGoReader(reader io.Reader) (GoReader, error) {
	return newGoReader(reader, nil)
}

func newGoReader(reader io.Reader, upstream io.Closer) (GoReader, error) {
	if reader == nil {
		return GoReader{}, fmt.Errorf("go2zig: reader is nil")
	}
	if file, ok := reader.(*os.File); ok {
		state := &_go2zigStreamState{file: file}
		if upstream != nil {
			state.owned = upstream
		}
		return GoReader{state: state}, nil
	}
	pr, pw, err := os.Pipe()
	if err != nil {
		return GoReader{}, err
	}
	state := &_go2zigStreamState{file: pr, owned: pr, upstream: upstream, done: make(chan error, 1)}
	go func() {
		_, err := io.Copy(pw, reader)
		if closeErr := pw.Close(); err == nil {
			err = closeErr
		}
		if state.upstream != nil {
			if closeErr := state.upstream.Close(); err == nil {
				err = closeErr
			}
		}
		state.done <- err
	}()
	return GoReader{state: state}, nil
}

func NewGoWriteCloser(writer io.WriteCloser) (GoWriter, error) {
	return newGoWriter(writer, writer)
}

func NewGoWriter(writer io.Writer) (GoWriter, error) {
	return newGoWriter(writer, nil)
}

func newGoWriter(writer io.Writer, upstream io.Closer) (GoWriter, error) {
	if writer == nil {
		return GoWriter{}, fmt.Errorf("go2zig: writer is nil")
	}
	if file, ok := writer.(*os.File); ok {
		state := &_go2zigStreamState{file: file}
		if upstream != nil {
			state.owned = upstream
		}
		return GoWriter{state: state}, nil
	}
	pr, pw, err := os.Pipe()
	if err != nil {
		return GoWriter{}, err
	}
	state := &_go2zigStreamState{file: pw, owned: pw, upstream: upstream, done: make(chan error, 1)}
	go func() {
		_, err := io.Copy(writer, pr)
		if closeErr := pr.Close(); err == nil {
			err = closeErr
		}
		if state.upstream != nil {
			if closeErr := state.upstream.Close(); err == nil {
				err = closeErr
			}
		}
		state.done <- err
	}()
	return GoWriter{state: state}, nil
}

func (v GoReader) handle() uintptr {
	return v.state.handle()
}

func (v GoWriter) handle() uintptr {
	return v.state.handle()
}

func (v GoReader) Close() error {
	return v.state.close(true)
}

func (v GoWriter) Close() error {
	return v.state.close(false)
}

func (v GoReader) Err() error {
	if v.state == nil {
		return nil
	}
	return v.state.wait()
}

func (v GoWriter) Err() error {
	if v.state == nil {
		return nil
	}
	return v.state.wait()
}

func _go2zigDefaultLibraryPath() string {
	_, file, _, ok := runtime.Caller(0)
	name := _go2zigDynamicLibraryName()
	if !ok {
		return name
	}
	return filepath.Join(filepath.Dir(file), name)
}

func (c *Go2ZigClient) Load() error {
	return c.rt.Load()
}

func _go2zigDynamicLibraryName() string {
	switch runtime.GOOS {
	case "windows":
		return "stream.dll"
	case "darwin":
		return "libstream.dylib"
	default:
		return "libstream.so"
	}
}

type _go2zigString struct {
	Ptr unsafe.Pointer
	Len uintptr
}

type _go2zigBytes struct {
	Ptr unsafe.Pointer
	Len uintptr
}

type _go2zigError struct {
	Code uint32
	Text _go2zigString
}

func _go2zigBool(v bool) uint8 {
	if v {
		return 1
	}
	return 0
}

func _go2zigFromBool(v uint8) bool {
	return v != 0
}

func _go2zigRefString(value string) _go2zigString {
	if len(value) == 0 {
		return _go2zigString{}
	}
	return _go2zigString{Ptr: unsafe.Pointer(unsafe.StringData(value)), Len: uintptr(len(value))}
}

func _go2zigRefBytes(value []byte) _go2zigBytes {
	if len(value) == 0 {
		return _go2zigBytes{}
	}
	return _go2zigBytes{Ptr: unsafe.Pointer(unsafe.SliceData(value)), Len: uintptr(len(value))}
}

func _go2zigOwnString(rt *_go2zigRuntime, value _go2zigString) string {
	_go2zigAssertSpan("String", value.Ptr, value.Len)
	if value.Ptr == nil {
		return ""
	}
	bytes := unsafe.Slice((*byte)(value.Ptr), int(value.Len))
	ret := string(bytes)
	rt.free(value.Ptr, value.Len)
	return ret
}

func _go2zigOwnBytes(rt *_go2zigRuntime, value _go2zigBytes) []byte {
	_go2zigAssertSpan("Bytes", value.Ptr, value.Len)
	if value.Ptr == nil {
		return nil
	}
	ret := append([]byte(nil), unsafe.Slice((*byte)(value.Ptr), int(value.Len))...)
	rt.free(value.Ptr, value.Len)
	return ret
}

func _go2zigAssertSpan(name string, ptr unsafe.Pointer, len uintptr) {
	if ptr == nil && len == 0 {
		return
	}
	if len == 0 {
		return
	}
	if ptr == nil {
		panic(fmt.Sprintf("go2zig: invalid %s buffer state ptr=%p len=%d", name, ptr, len))
	}
}

func _go2zigOwnError(rt *_go2zigRuntime, value _go2zigError) error {
	if value.Code == 0 {
		return nil
	}
	return &Go2ZigError{Code: value.Code, Message: _go2zigOwnString(rt, value.Text)}
}

type Go2ZigError struct {
	Code    uint32
	Message string
}

func (e *Go2ZigError) Error() string {
	if e == nil {
		return "<nil>"
	}
	if e.Message != "" {
		return e.Message
	}
	return fmt.Sprintf("zig error code %d", e.Code)
}

func _go2zigKeep(values []any) {
	for _, value := range values {
		runtime.KeepAlive(value)
	}
}

type _go2zigCallCopyStream struct {
	reader uintptr
	writer uintptr
	out    uint64
}

func (c *Go2ZigClient) CopyStream(reader GoReader, writer GoWriter) uint64 {
	var frame _go2zigCallCopyStream
	frame.reader = reader.handle()
	defer func() {
		if err := reader.Close(); err != nil {
			panic(err)
		}
	}()
	frame.writer = writer.handle()
	defer func() {
		if err := writer.Close(); err != nil {
			panic(err)
		}
	}()
	c.rt.call(c.rt.procCopyStream, unsafe.Pointer(&frame))
	runtime.KeepAlive(reader)
	runtime.KeepAlive(writer)
	return uint64(frame.out)
}

func CopyStream(reader GoReader, writer GoWriter) uint64 {
	return Default.CopyStream(reader, writer)
}
