// Code generated by go2zig. DO NOT EDIT.
const api = @import("./api.zig");
const impl = @import("lib.zig");
const rt = @import("go2zig_runtime.zig");

pub export fn go2zig_free_buf(ptr: ?*anyopaque, len: usize) void {
    rt.freeBuf(ptr, len);
}

pub const Go2ZigCallCopyStream = extern struct {
    reader: usize,
    writer: usize,
    out: u64,
    err: rt.ErrorInfo,
};

pub export fn go2zig_call_copy_stream(frame: *Go2ZigCallCopyStream) void {
    frame.err = rt.okError();
    const result = impl.copy_stream(frame.reader, frame.writer) catch |err| {
        frame.err = rt.makeError(err);
        return;
    };
    frame.out = result;
}

