// Code generated by go2zig. DO NOT EDIT.
const std = @import("std");
const builtin = @import("builtin");
const api = @import("./api.zig");

pub const ErrorInfo = extern struct {
    code: u32,
    text: api.String,
};

pub inline fn asSlice(value: api.String) []const u8 {
    if (value.len == 0) return "";
    return value.ptr[0..value.len];
}

pub inline fn asBytes(value: api.Bytes) []const u8 {
    if (value.len == 0) return &.{};
    return value.ptr[0..value.len];
}

pub fn ownString(value: []const u8) api.String {
    if (value.len == 0) return .{ .ptr = undefined, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(u8, value.len) catch @panic("go2zig: alloc string failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub fn ownBytes(value: []const u8) api.Bytes {
    if (value.len == 0) return .{ .ptr = undefined, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(u8, value.len) catch @panic("go2zig: alloc bytes failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub fn freeBuf(ptr: ?*anyopaque, len: usize) void {
    if (len == 0 or ptr == null) return;
    const buf = @as([*]u8, @ptrCast(ptr.?))[0..len];
    std.heap.smp_allocator.free(buf);
}

pub fn okError() ErrorInfo {
    return .{ .code = 0, .text = .{ .ptr = undefined, .len = 0 } };
}

const stream_handle_mask: usize = 0x3;
const stream_handle_direct_reader: usize = 0x1;
const stream_handle_direct_writer: usize = 0x2;

const DirectReaderState = extern struct {
    ptr: ?*const anyopaque,
    len: usize,
    pos: usize,
};

const DirectWriterState = extern struct {
    ptr: ?*anyopaque,
    len: usize,
    cap: usize,
};

inline fn streamHandleFromUsize(value: usize) std.Io.File.Handle {
    return switch (@typeInfo(std.Io.File.Handle)) {
        .pointer => @as(std.Io.File.Handle, @ptrFromInt(value)),
        else => @as(std.Io.File.Handle, @intCast(value)),
    };
}

inline fn streamHandleFromEncoded(value: usize) std.Io.File.Handle {
    return streamHandleFromUsize((value >> 2) - 1);
}

inline fn streamFileFromEncoded(value: usize) std.Io.File {
    return .{
        .handle = streamHandleFromEncoded(value),
        .flags = .{ .nonblocking = false },
    };
}

pub inline fn streamFile(value: usize) ?std.Io.File {
    if (value == 0) return null;
    if ((value & stream_handle_mask) != 0) return null;
    return streamFileFromEncoded(value);
}

inline fn directReaderStateFromHandle(value: usize) *DirectReaderState {
    return @ptrFromInt(value & ~stream_handle_mask);
}

inline fn directWriterStateFromHandle(value: usize) *DirectWriterState {
    return @ptrFromInt(value & ~stream_handle_mask);
}

const stream_is_windows = builtin.os.tag == .windows;

inline fn streamReadCompat(handle: std.Io.File.Handle, buffer: []u8) anyerror!usize {
    if (stream_is_windows) {
        const io = std.Io.Threaded.global_single_threaded.io();
        const file: std.Io.File = .{
            .handle = handle,
            .flags = .{ .nonblocking = false },
        };
        return file.readStreaming(io, &.{buffer}) catch |err| switch (err) {
            error.EndOfStream => 0,
            else => err,
        };
    }
    return std.posix.read(handle, buffer);
}

inline fn streamWriteCompat(handle: std.Io.File.Handle, buffer: []const u8) anyerror!usize {
    if (stream_is_windows) {
        const io = std.Io.Threaded.global_single_threaded.io();
        const file: std.Io.File = .{
            .handle = handle,
            .flags = .{ .nonblocking = false },
        };
        return file.writeStreaming(io, &.{}, &.{buffer}, 1);
    }
    while (true) {
        const rc = std.posix.system.write(handle, buffer.ptr, buffer.len);
        switch (std.posix.errno(rc)) {
            .SUCCESS => return @intCast(rc),
            .INTR => continue,
            .AGAIN => return error.WouldBlock,
            .ACCES => return error.AccessDenied,
            .PERM => return error.PermissionDenied,
            .PIPE => return error.BrokenPipe,
            .NOSPC => return error.NoSpaceLeft,
            .DQUOT => return error.DiskQuota,
            .IO => return error.InputOutput,
            .NOBUFS, .NOMEM => return error.SystemResources,
            .FBIG => return error.FileTooBig,
            .BUSY => return error.DeviceBusy,
            .NXIO => return error.NoDevice,
            .TXTBSY => return error.FileBusy,
            .BADF => return error.Unexpected,
            else => |err| return std.posix.unexpectedErrno(err),
        }
    }
}

pub fn streamRead(reader: usize, buffer: []u8) error{StreamReadFailed, EndOfStream}!usize {
    if (reader == 0) return error.StreamReadFailed;
    const tag = reader & stream_handle_mask;
    if (tag == stream_handle_direct_reader) {
        const state = directReaderStateFromHandle(reader);
        if (state.ptr == null or state.pos >= state.len) return error.EndOfStream;
        const remaining = state.len - state.pos;
        const n = @min(buffer.len, remaining);
        const src = @as([*]const u8, @ptrCast(state.ptr.?))[state.pos..][0..n];
        @memcpy(buffer[0..n], src);
        state.pos += n;
        return n;
    }
    if (tag != 0) return error.StreamReadFailed;
    const n = streamReadCompat(streamHandleFromEncoded(reader), buffer) catch { return error.StreamReadFailed; };
    if (n == 0) return error.EndOfStream;
    return n;
}

pub fn streamWrite(writer: usize, buffer: []const u8) error{StreamWriteFailed}!usize {
    if (writer == 0) return error.StreamWriteFailed;
    const tag = writer & stream_handle_mask;
    if (tag == stream_handle_direct_writer) {
        const state = directWriterStateFromHandle(writer);
        if (state.ptr == null or state.len > state.cap) return error.StreamWriteFailed;
        const available = state.cap - state.len;
        if (buffer.len > available) return error.StreamWriteFailed;
        const dst = @as([*]u8, @ptrCast(state.ptr.?))[state.len..][0..buffer.len];
        @memcpy(dst, buffer);
        state.len += buffer.len;
        return buffer.len;
    }
    if (tag != 0) return error.StreamWriteFailed;
    return streamWriteCompat(streamHandleFromEncoded(writer), buffer) catch { return error.StreamWriteFailed; };
}

pub fn makeError(err: anyerror) ErrorInfo {
    return .{
        .code = @intFromError(err),
        .text = ownString(@errorName(err)),
    };
}
