package generator

import (
	"fmt"
	"go/format"
	"path/filepath"
	"strings"

	"go2zig/internal/model"
	"go2zig/internal/names"
)

type Config struct {
	PackageName string
	LibraryName string
	APIModule   string
	ImplModule  string
}

func Render(api *model.API, cfg Config) ([]byte, error) {
	if cfg.PackageName == "" {
		cfg.PackageName = "main"
	}
	if cfg.LibraryName == "" {
		cfg.LibraryName = "go2zig"
	}

	var body strings.Builder
	body.WriteString("// Code generated by go2zig. DO NOT EDIT.\n")
	body.WriteString("//go:build amd64 && (windows || linux)\n\n")
	body.WriteString("package ")
	body.WriteString(cfg.PackageName)
	body.WriteString("\n\n")
	body.WriteString("import (\n")
	body.WriteString("\t\"fmt\"\n")
	body.WriteString("\t\"path/filepath\"\n")
	body.WriteString("\t\"runtime\"\n")
	body.WriteString("\t\"sync\"\n")
	body.WriteString("\t\"unsafe\"\n\n")
	body.WriteString("\t\"go2zig/asmcall\"\n")
	body.WriteString("\t\"go2zig/dynlib\"\n")
	body.WriteString(")\n\n")

	body.WriteString("type Go2ZigClient struct {\n\trt *_go2zigRuntime\n}\n\n")
	body.WriteString("func NewGo2ZigClient(path string) *Go2ZigClient {\n")
	body.WriteString("\treturn &Go2ZigClient{rt: &_go2zigRuntime{path: path}}\n")
	body.WriteString("}\n\n")
	body.WriteString("var Default = NewGo2ZigClient(\"\")\n\n")
	body.WriteString("type _go2zigRuntime struct {\n")
	body.WriteString("\tpath string\n")
	body.WriteString("\tonce sync.Once\n")
	body.WriteString("\tlib *dynlib.Library\n")
	body.WriteString("\tfreeBuf uintptr\n")
	for _, fn := range api.Funcs {
		body.WriteString("\t")
		body.WriteString(procFieldName(fn))
		body.WriteString(" uintptr\n")
	}
	body.WriteString("\terr error\n")
	body.WriteString("}\n\n")
	body.WriteString("func (rt *_go2zigRuntime) Load() error {\n")
	body.WriteString("\trt.once.Do(func() {\n")
	body.WriteString("\t\tpath := rt.path\n")
	body.WriteString("\t\tif path == \"\" {\n")
	body.WriteString("\t\t\tpath = _go2zigDefaultLibraryPath()\n")
	body.WriteString("\t\t}\n")
	body.WriteString("\t\tlib, err := dynlib.Load(path)\n")
	body.WriteString("\t\tif err != nil {\n")
	body.WriteString("\t\t\trt.err = fmt.Errorf(\"go2zig: load %s: %w\", path, err)\n")
	body.WriteString("\t\t\treturn\n")
	body.WriteString("\t\t}\n")
	body.WriteString("\t\trt.lib = lib\n")
	body.WriteString("\t\tif rt.freeBuf, err = lib.Lookup(\"go2zig_free_buf\"); err != nil {\n")
	body.WriteString("\t\t\trt.err = fmt.Errorf(\"go2zig: lookup go2zig_free_buf: %w\", err)\n")
	body.WriteString("\t\t\treturn\n")
	body.WriteString("\t\t}\n")
	for _, fn := range api.Funcs {
		body.WriteString("\t\tif rt.")
		body.WriteString(procFieldName(fn))
		body.WriteString(", err = lib.Lookup(\"")
		body.WriteString(procSymbolName(fn))
		body.WriteString("\"); err != nil {\n")
		body.WriteString("\t\t\trt.err = fmt.Errorf(\"go2zig: lookup ")
		body.WriteString(procSymbolName(fn))
		body.WriteString(": %w\", err)\n")
		body.WriteString("\t\t\treturn\n")
		body.WriteString("\t\t}\n")
	}
	body.WriteString("\t})\n")
	body.WriteString("\treturn rt.err\n")
	body.WriteString("}\n\n")
	body.WriteString("func (rt *_go2zigRuntime) free(ptr unsafe.Pointer, len uintptr) {\n")
	body.WriteString("\tif ptr == nil {\n\t\treturn\n\t}\n")
	body.WriteString("\tif err := rt.Load(); err != nil {\n\t\tpanic(err)\n\t}\n")
	body.WriteString("\tasmcall.CallFuncG0P2(unsafe.Pointer(rt.freeBuf), ptr, unsafe.Pointer(len))\n")
	body.WriteString("}\n\n")
	body.WriteString("func (rt *_go2zigRuntime) call(proc uintptr, frame unsafe.Pointer) {\n")
	body.WriteString("\tif err := rt.Load(); err != nil {\n\t\tpanic(err)\n\t}\n")
	body.WriteString("\tasmcall.CallFuncG0P1(unsafe.Pointer(proc), frame)\n")
	body.WriteString("}\n\n")
	body.WriteString("func _go2zigDefaultLibraryPath() string {\n")
	body.WriteString("\t_, file, _, ok := runtime.Caller(0)\n")
	body.WriteString("\tname := _go2zigDynamicLibraryName()\n")
	body.WriteString("\tif !ok {\n")
	body.WriteString("\t\treturn name\n")
	body.WriteString("\t}\n")
	body.WriteString("\treturn filepath.Join(filepath.Dir(file), name)\n")
	body.WriteString("}\n\n")
	body.WriteString("func (c *Go2ZigClient) Load() error {\n\treturn c.rt.Load()\n}\n\n")
	body.WriteString("func _go2zigDynamicLibraryName() string {\n")
	body.WriteString("\tswitch runtime.GOOS {\n")
	body.WriteString("\tcase \"windows\":\n")
	body.WriteString("\t\treturn \"")
	body.WriteString(DynamicLibraryFilename(cfg.LibraryName, "windows"))
	body.WriteString("\"\n")
	body.WriteString("\tcase \"darwin\":\n")
	body.WriteString("\t\treturn \"")
	body.WriteString(DynamicLibraryFilename(cfg.LibraryName, "darwin"))
	body.WriteString("\"\n")
	body.WriteString("\tdefault:\n")
	body.WriteString("\t\treturn \"")
	body.WriteString(DynamicLibraryFilename(cfg.LibraryName, "linux"))
	body.WriteString("\"\n")
	body.WriteString("\t}\n")
	body.WriteString("}\n\n")

	body.WriteString("type _go2zigString struct {\n\tPtr unsafe.Pointer\n\tLen uintptr\n}\n\n")
	body.WriteString("type _go2zigBytes struct {\n\tPtr unsafe.Pointer\n\tLen uintptr\n}\n\n")
	body.WriteString("type _go2zigError struct {\n\tCode uint32\n\tText _go2zigString\n}\n\n")
	body.WriteString("func _go2zigBool(v bool) uint8 {\n\tif v {\n\t\treturn 1\n\t}\n\treturn 0\n}\n\n")
	body.WriteString("func _go2zigFromBool(v uint8) bool {\n\treturn v != 0\n}\n\n")
	body.WriteString("func _go2zigRefString(value string) _go2zigString {\n")
	body.WriteString("\tif len(value) == 0 {\n\t\treturn _go2zigString{}\n\t}\n")
	body.WriteString("\treturn _go2zigString{Ptr: unsafe.Pointer(unsafe.StringData(value)), Len: uintptr(len(value))}\n")
	body.WriteString("}\n\n")
	body.WriteString("func _go2zigRefBytes(value []byte) _go2zigBytes {\n")
	body.WriteString("\tif len(value) == 0 {\n\t\treturn _go2zigBytes{}\n\t}\n")
	body.WriteString("\treturn _go2zigBytes{Ptr: unsafe.Pointer(unsafe.SliceData(value)), Len: uintptr(len(value))}\n")
	body.WriteString("}\n\n")
	body.WriteString("func _go2zigOwnString(rt *_go2zigRuntime, value _go2zigString) string {\n")
	body.WriteString("\tif value.Ptr == nil || value.Len == 0 {\n\t\treturn \"\"\n\t}\n")
	body.WriteString("\tbytes := unsafe.Slice((*byte)(value.Ptr), int(value.Len))\n")
	body.WriteString("\tret := string(bytes)\n")
	body.WriteString("\trt.free(value.Ptr, value.Len)\n")
	body.WriteString("\treturn ret\n")
	body.WriteString("}\n\n")
	body.WriteString("func _go2zigOwnBytes(rt *_go2zigRuntime, value _go2zigBytes) []byte {\n")
	body.WriteString("\tif value.Ptr == nil || value.Len == 0 {\n\t\treturn nil\n\t}\n")
	body.WriteString("\tret := append([]byte(nil), unsafe.Slice((*byte)(value.Ptr), int(value.Len))...)\n")
	body.WriteString("\trt.free(value.Ptr, value.Len)\n")
	body.WriteString("\treturn ret\n")
	body.WriteString("}\n\n")
	body.WriteString("func _go2zigOwnError(rt *_go2zigRuntime, value _go2zigError) error {\n")
	body.WriteString("\tif value.Code == 0 {\n\t\treturn nil\n\t}\n")
	body.WriteString("\treturn &Go2ZigError{Code: value.Code, Message: _go2zigOwnString(rt, value.Text)}\n")
	body.WriteString("}\n\n")
	body.WriteString("type Go2ZigError struct {\n\tCode uint32\n\tMessage string\n}\n\n")
	body.WriteString("func (e *Go2ZigError) Error() string {\n")
	body.WriteString("\tif e == nil {\n\t\treturn \"<nil>\"\n\t}\n")
	body.WriteString("\tif e.Message != \"\" {\n\t\treturn e.Message\n\t}\n")
	body.WriteString("\treturn fmt.Sprintf(\"zig error code %d\", e.Code)\n")
	body.WriteString("}\n\n")

	for _, item := range api.Structs {
		body.WriteString(renderPublicStruct(item))
		body.WriteString(renderABIStruct(item))
		body.WriteString(renderRefStruct(item))
		body.WriteString(renderOwnStruct(item))
	}

	for _, fn := range api.Funcs {
		body.WriteString(renderFrameStruct(fn))
	}

	for _, fn := range api.Funcs {
		body.WriteString(renderMethod(fn))
		body.WriteString("\n")
		body.WriteString(renderTopLevel(fn))
		body.WriteString("\n")
	}

	fmted, err := format.Source([]byte(body.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated go: %w", err)
	}
	return fmted, nil
}

func RenderZigRuntime(cfg Config) []byte {
	apiModule := cfg.APIModule
	if apiModule == "" {
		apiModule = "api.zig"
	}
	var body strings.Builder
	body.WriteString("// Code generated by go2zig. DO NOT EDIT.\n")
	body.WriteString("const std = @import(\"std\");\n")
	body.WriteString("const api = @import(\"")
	body.WriteString(escapeZigString(apiModule))
	body.WriteString("\");\n\n")
	body.WriteString("pub const ErrorInfo = extern struct {\n")
	body.WriteString("    code: u32,\n")
	body.WriteString("    text: api.String,\n")
	body.WriteString("};\n\n")
	body.WriteString("pub inline fn asSlice(value: api.String) []const u8 {\n")
	body.WriteString("    if (value.len == 0) return \"\";\n")
	body.WriteString("    return value.ptr[0..value.len];\n")
	body.WriteString("}\n\n")
	body.WriteString("pub inline fn asBytes(value: api.Bytes) []const u8 {\n")
	body.WriteString("    if (value.len == 0) return &.{};\n")
	body.WriteString("    return value.ptr[0..value.len];\n")
	body.WriteString("}\n\n")
	body.WriteString("pub fn ownString(value: []const u8) api.String {\n")
	body.WriteString("    if (value.len == 0) return .{ .ptr = undefined, .len = 0 };\n")
	body.WriteString("    const buf = std.heap.smp_allocator.alloc(u8, value.len) catch @panic(\"go2zig: alloc string failed\");\n")
	body.WriteString("    @memcpy(buf, value);\n")
	body.WriteString("    return .{ .ptr = buf.ptr, .len = buf.len };\n")
	body.WriteString("}\n\n")
	body.WriteString("pub fn ownBytes(value: []const u8) api.Bytes {\n")
	body.WriteString("    if (value.len == 0) return .{ .ptr = undefined, .len = 0 };\n")
	body.WriteString("    const buf = std.heap.smp_allocator.alloc(u8, value.len) catch @panic(\"go2zig: alloc bytes failed\");\n")
	body.WriteString("    @memcpy(buf, value);\n")
	body.WriteString("    return .{ .ptr = buf.ptr, .len = buf.len };\n")
	body.WriteString("}\n\n")
	body.WriteString("pub fn freeBuf(ptr: ?*anyopaque, len: usize) void {\n")
	body.WriteString("    if (len == 0 or ptr == null) return;\n")
	body.WriteString("    const buf = @as([*]u8, @ptrCast(ptr.?))[0..len];\n")
	body.WriteString("    std.heap.smp_allocator.free(buf);\n")
	body.WriteString("}\n")
	body.WriteString("\n")
	body.WriteString("pub fn okError() ErrorInfo {\n")
	body.WriteString("    return .{ .code = 0, .text = .{ .ptr = undefined, .len = 0 } };\n")
	body.WriteString("}\n\n")
	body.WriteString("pub fn makeError(err: anyerror) ErrorInfo {\n")
	body.WriteString("    return .{\n")
	body.WriteString("        .code = @intFromError(err),\n")
	body.WriteString("        .text = ownString(@errorName(err)),\n")
	body.WriteString("    };\n")
	body.WriteString("}\n")
	return []byte(body.String())
}

func RenderZigBridge(api *model.API, cfg Config) []byte {
	apiModule := cfg.APIModule
	if apiModule == "" {
		apiModule = "api.zig"
	}
	implModule := cfg.ImplModule
	if implModule == "" {
		implModule = "lib.zig"
	}
	var body strings.Builder
	body.WriteString("// Code generated by go2zig. DO NOT EDIT.\n")
	body.WriteString("const api = @import(\"")
	body.WriteString(escapeZigString(apiModule))
	body.WriteString("\");\n")
	body.WriteString("const impl = @import(\"")
	body.WriteString(escapeZigString(implModule))
	body.WriteString("\");\n")
	body.WriteString("const rt = @import(\"go2zig_runtime.zig\");\n\n")
	body.WriteString("pub export fn go2zig_free_buf(ptr: ?*anyopaque, len: usize) void {\n")
	body.WriteString("    rt.freeBuf(ptr, len);\n")
	body.WriteString("}\n\n")
	for _, fn := range api.Funcs {
		body.WriteString("pub const ")
		body.WriteString(zigFrameName(fn))
		body.WriteString(" = extern struct {\n")
		fields := frameFields(fn)
		for _, field := range fields {
			body.WriteString("    ")
			body.WriteString(field.name)
			body.WriteString(": ")
			body.WriteString(field.typ)
			body.WriteString(",\n")
		}
		body.WriteString("};\n\n")
		body.WriteString("pub export fn ")
		body.WriteString(procSymbolName(fn))
		body.WriteString("(frame: *")
		body.WriteString(zigFrameName(fn))
		body.WriteString(") void {\n")
		if fn.CanErr {
			body.WriteString("    frame.err = rt.okError();\n")
			body.WriteString("    const result = impl.")
			body.WriteString(fn.Name)
			body.WriteString("(")
			for i, param := range fn.Params {
				if i > 0 {
					body.WriteString(", ")
				}
				body.WriteString("frame.")
				body.WriteString(param.Name)
			}
			body.WriteString(") catch |err| {\n")
			body.WriteString("        frame.err = rt.makeError(err);\n")
			body.WriteString("        return;\n")
			body.WriteString("    };\n")
			if fn.Return.Kind != model.TypeVoid {
				body.WriteString("    frame.out = result;\n")
			}
		} else {
			if fn.Return.Kind != model.TypeVoid {
				body.WriteString("    frame.out = impl.")
				body.WriteString(fn.Name)
				body.WriteString("(")
			} else {
				body.WriteString("    impl.")
				body.WriteString(fn.Name)
				body.WriteString("(")
			}
			for i, param := range fn.Params {
				if i > 0 {
					body.WriteString(", ")
				}
				body.WriteString("frame.")
				body.WriteString(param.Name)
			}
			body.WriteString(");\n")
		}
		body.WriteString("}\n\n")
	}
	return []byte(body.String())
}

func LibraryNameFromPath(path string) string {
	base := filepath.Base(path)
	ext := filepath.Ext(base)
	if ext != "" {
		base = strings.TrimSuffix(base, ext)
	}
	return base
}

func DynamicLibraryFilename(name, goos string) string {
	clean := strings.TrimSpace(name)
	if clean == "" {
		clean = "go2zig"
	}
	switch goos {
	case "windows":
		return clean + ".dll"
	case "darwin":
		return "lib" + clean + ".dylib"
	default:
		return "lib" + clean + ".so"
	}
}

type zigField struct {
	name string
	typ  string
}

func frameFields(fn *model.Function) []zigField {
	fields := make([]zigField, 0, len(fn.Params)+1)
	for _, param := range fn.Params {
		fields = append(fields, zigField{name: param.Name, typ: zigType(param.Type)})
	}
	if fn.Return.Kind != model.TypeVoid {
		fields = append(fields, zigField{name: "out", typ: zigType(fn.Return)})
	}
	if fn.CanErr {
		fields = append(fields, zigField{name: "err", typ: "rt.ErrorInfo"})
	}
	if len(fields) == 0 {
		fields = append(fields, zigField{name: "reserved", typ: "usize"})
	}
	return fields
}

func renderPublicStruct(item *model.Struct) string {
	var b strings.Builder
	b.WriteString("type ")
	b.WriteString(item.Name)
	b.WriteString(" struct {\n")
	for _, field := range item.Fields {
		b.WriteString("\t")
		b.WriteString(names.Exported(field.Name))
		b.WriteString(" ")
		b.WriteString(goType(field.Type))
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")
	return b.String()
}

func renderABIStruct(item *model.Struct) string {
	var b strings.Builder
	b.WriteString("type ")
	b.WriteString(abiStructName(item.Name))
	b.WriteString(" struct {\n")
	for _, field := range item.Fields {
		b.WriteString("\t")
		b.WriteString(field.Name)
		b.WriteString(" ")
		b.WriteString(abiType(field.Type))
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")
	return b.String()
}

func renderRefStruct(item *model.Struct) string {
	var b strings.Builder
	b.WriteString("func ")
	b.WriteString(refFuncName(item.Name))
	b.WriteString("(value ")
	b.WriteString(item.Name)
	b.WriteString(") ")
	b.WriteString(abiStructName(item.Name))
	b.WriteString(" {\n")
	b.WriteString("\treturn ")
	b.WriteString(abiStructName(item.Name))
	b.WriteString("{\n")
	for _, field := range item.Fields {
		b.WriteString("\t\t")
		b.WriteString(field.Name)
		b.WriteString(": ")
		b.WriteString(refExpr(field.Type, "value."+names.Exported(field.Name)))
		b.WriteString(",\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	return b.String()
}

func renderOwnStruct(item *model.Struct) string {
	var b strings.Builder
	b.WriteString("func ")
	b.WriteString(ownFuncName(item.Name))
	b.WriteString("(rt *_go2zigRuntime, value ")
	b.WriteString(abiStructName(item.Name))
	b.WriteString(") ")
	b.WriteString(item.Name)
	b.WriteString(" {\n")
	b.WriteString("\treturn ")
	b.WriteString(item.Name)
	b.WriteString("{\n")
	for _, field := range item.Fields {
		b.WriteString("\t\t")
		b.WriteString(names.Exported(field.Name))
		b.WriteString(": ")
		b.WriteString(ownExprRT("rt", field.Type, "value."+field.Name))
		b.WriteString(",\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	return b.String()
}

func renderFrameStruct(fn *model.Function) string {
	var b strings.Builder
	b.WriteString("type ")
	b.WriteString(goFrameName(fn))
	b.WriteString(" struct {\n")
	fields := frameFields(fn)
	for _, field := range fields {
		b.WriteString("\t")
		b.WriteString(field.name)
		b.WriteString(" ")
		b.WriteString(goFrameFieldType(field.typ))
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")
	return b.String()
}

func renderMethod(fn *model.Function) string {
	goName := names.Exported(fn.Name)
	var b strings.Builder
	b.WriteString("func (c *Go2ZigClient) ")
	b.WriteString(goName)
	b.WriteString("(")
	for i, param := range fn.Params {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(goParamName(param.Name))
		b.WriteString(" ")
		b.WriteString(goType(param.Type))
	}
	b.WriteString(")")
	if fn.CanErr {
		if fn.Return.Kind != model.TypeVoid {
			b.WriteString(" (")
			b.WriteString(goType(fn.Return))
			b.WriteString(", error)")
		} else {
			b.WriteString(" error")
		}
	} else if fn.Return.Kind != model.TypeVoid {
		b.WriteString(" ")
		b.WriteString(goType(fn.Return))
	}
	b.WriteString(" {\n")
	b.WriteString("\tvar frame ")
	b.WriteString(goFrameName(fn))
	b.WriteString("\n")
	for _, param := range fn.Params {
		b.WriteString("\tframe.")
		b.WriteString(param.Name)
		b.WriteString(" = ")
		b.WriteString(refExpr(param.Type, goParamName(param.Name)))
		b.WriteString("\n")
	}
	b.WriteString("\tc.rt.call(c.rt.")
	b.WriteString(procFieldName(fn))
	b.WriteString(", unsafe.Pointer(&frame))\n")
	for _, param := range fn.Params {
		b.WriteString("\truntime.KeepAlive(")
		b.WriteString(goParamName(param.Name))
		b.WriteString(")\n")
	}
	if fn.CanErr {
		b.WriteString("\tif err := _go2zigOwnError(c.rt, frame.err); err != nil {\n")
		if fn.Return.Kind != model.TypeVoid {
			b.WriteString("\t\tvar zero ")
			b.WriteString(goType(fn.Return))
			b.WriteString("\n\t\treturn zero, err\n")
		} else {
			b.WriteString("\t\treturn err\n")
		}
		b.WriteString("\t}\n")
	}
	if fn.Return.Kind != model.TypeVoid {
		b.WriteString("\treturn ")
		b.WriteString(ownExprRT("c.rt", fn.Return, "frame.out"))
		if fn.CanErr {
			b.WriteString(", nil")
		}
		b.WriteString("\n")
	} else if fn.CanErr {
		b.WriteString("\treturn nil\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func renderTopLevel(fn *model.Function) string {
	goName := names.Exported(fn.Name)
	var b strings.Builder
	b.WriteString("func ")
	b.WriteString(goName)
	b.WriteString("(")
	for i, param := range fn.Params {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(goParamName(param.Name))
		b.WriteString(" ")
		b.WriteString(goType(param.Type))
	}
	b.WriteString(")")
	if fn.CanErr {
		if fn.Return.Kind != model.TypeVoid {
			b.WriteString(" (")
			b.WriteString(goType(fn.Return))
			b.WriteString(", error)")
		} else {
			b.WriteString(" error")
		}
	} else if fn.Return.Kind != model.TypeVoid {
		b.WriteString(" ")
		b.WriteString(goType(fn.Return))
	}
	b.WriteString(" {\n\t")
	if fn.Return.Kind != model.TypeVoid || fn.CanErr {
		b.WriteString("return ")
	}
	b.WriteString("Default.")
	b.WriteString(goName)
	b.WriteString("(")
	for i, param := range fn.Params {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(goParamName(param.Name))
	}
	b.WriteString(")\n}\n")
	return b.String()
}

func refExpr(t model.TypeRef, expr string) string {
	switch t.Kind {
	case model.TypePrimitive:
		if t.Name == "bool" {
			return "_go2zigBool(" + expr + ")"
		}
		return abiType(t) + "(" + expr + ")"
	case model.TypeString:
		return "_go2zigRefString(" + expr + ")"
	case model.TypeBytes:
		return "_go2zigRefBytes(" + expr + ")"
	case model.TypeStruct:
		return refFuncName(t.Name) + "(" + expr + ")"
	default:
		return expr
	}
}

func ownExprRT(rtName string, t model.TypeRef, expr string) string {
	switch t.Kind {
	case model.TypePrimitive:
		if t.Name == "bool" {
			return "_go2zigFromBool(" + expr + ")"
		}
		return goType(t) + "(" + expr + ")"
	case model.TypeString:
		return "_go2zigOwnString(" + rtName + ", " + expr + ")"
	case model.TypeBytes:
		return "_go2zigOwnBytes(" + rtName + ", " + expr + ")"
	case model.TypeStruct:
		return ownFuncName(t.Name) + "(" + rtName + ", " + expr + ")"
	default:
		return expr
	}
}

func goType(t model.TypeRef) string {
	switch t.Kind {
	case model.TypePrimitive:
		return t.Primitive.Go
	case model.TypeString:
		return "string"
	case model.TypeBytes:
		return "[]byte"
	case model.TypeStruct:
		return t.Name
	case model.TypeVoid:
		return "struct{}"
	default:
		return ""
	}
}

func abiType(t model.TypeRef) string {
	switch t.Kind {
	case model.TypePrimitive:
		if t.Name == "bool" {
			return "uint8"
		}
		return t.Primitive.Go
	case model.TypeString:
		return "_go2zigString"
	case model.TypeBytes:
		return "_go2zigBytes"
	case model.TypeStruct:
		return abiStructName(t.Name)
	default:
		return "struct{}"
	}
}

func zigType(t model.TypeRef) string {
	switch t.Kind {
	case model.TypePrimitive:
		return t.Primitive.Zig
	case model.TypeString, model.TypeBytes, model.TypeStruct:
		return "api." + t.TypeName()
	default:
		return "void"
	}
}

func abiStructName(name string) string { return "_go2zig" + name }
func refFuncName(name string) string   { return "_go2zigRef" + name }
func ownFuncName(name string) string   { return "_go2zigOwn" + name }
func goFrameName(fn *model.Function) string {
	return "_go2zigCall" + names.Exported(fn.Name)
}
func zigFrameName(fn *model.Function) string {
	return "Go2ZigCall" + names.Exported(fn.Name)
}
func procFieldName(fn *model.Function) string  { return "proc" + names.Exported(fn.Name) }
func procSymbolName(fn *model.Function) string { return "go2zig_call_" + fn.Name }

func goFrameFieldType(zigType string) string {
	switch zigType {
	case "api.String":
		return "_go2zigString"
	case "api.Bytes":
		return "_go2zigBytes"
	case "rt.ErrorInfo":
		return "_go2zigError"
	case "usize":
		return "uintptr"
	default:
		if strings.HasPrefix(zigType, "api.") {
			return abiStructName(strings.TrimPrefix(zigType, "api."))
		}
		if zigType == "bool" {
			return "uint8"
		}
		return zigType
	}
}

func goParamName(name string) string {
	value := names.LowerCamel(name)
	if value == "" {
		return "arg"
	}
	switch value {
	case "type", "func", "map", "var", "range", "select", "defer", "go", "chan", "package", "import", "return":
		return value + "Value"
	default:
		return value
	}
}

func escapeZigString(value string) string {
	return strings.ReplaceAll(value, "\\", "\\\\")
}
