package generator

import (
	"fmt"
	"go/format"
	"path/filepath"
	"strings"

	"go2zig/internal/model"
	"go2zig/internal/names"
)

type Config struct {
	PackageName string
	LibraryName string
}

func Render(api *model.API, cfg Config) ([]byte, error) {
	if cfg.PackageName == "" {
		cfg.PackageName = "main"
	}
	if cfg.LibraryName == "" {
		cfg.LibraryName = "go2zig"
	}
	ordered, err := api.SortedStructs()
	if err != nil {
		return nil, err
	}

	var body strings.Builder
	body.WriteString("// Code generated by go2zig. DO NOT EDIT.\n")
	body.WriteString("//go:build cgo\n\n")
	body.WriteString("package ")
	body.WriteString(cfg.PackageName)
	body.WriteString("\n\n")
	body.WriteString("/*\n")
	body.WriteString("#cgo LDFLAGS: -L${SRCDIR} -l")
	body.WriteString(cgoLibraryName(cfg.LibraryName))
	body.WriteString("\n")
	body.WriteString("#include <stdbool.h>\n#include <stdint.h>\n#include <stddef.h>\n#include <stdlib.h>\n\n")
	body.WriteString("typedef struct Go2ZigString {\n\tconst uint8_t *ptr;\n\tsize_t len;\n} Go2ZigString;\n\n")
	body.WriteString("typedef struct Go2ZigBytes {\n\tconst uint8_t *ptr;\n\tsize_t len;\n} Go2ZigBytes;\n\n")
	for _, item := range ordered {
		body.WriteString("typedef struct ")
		body.WriteString(item.Name)
		body.WriteString(" {\n")
		for _, field := range item.Fields {
			body.WriteString("\t")
			body.WriteString(cType(field.Type))
			body.WriteString(" ")
			body.WriteString(field.Name)
			body.WriteString(";\n")
		}
		body.WriteString("} ")
		body.WriteString(item.Name)
		body.WriteString(";\n\n")
	}
	body.WriteString("extern void go2zig_free_buf(void *ptr, size_t len);\n")
	for _, fn := range api.Funcs {
		body.WriteString("extern ")
		body.WriteString(cType(fn.Return))
		body.WriteString(" ")
		body.WriteString(fn.Name)
		body.WriteString("(")
		if len(fn.Params) == 0 {
			body.WriteString("void")
		} else {
			for i, param := range fn.Params {
				if i > 0 {
					body.WriteString(", ")
				}
				body.WriteString(cType(param.Type))
				body.WriteString(" ")
				body.WriteString(param.Name)
			}
		}
		body.WriteString(");\n")
	}
	body.WriteString("*/\n")
	body.WriteString("import \"C\"\n\n")
	body.WriteString("import (\n\t\"unsafe\"\n)\n\n")
	body.WriteString("type Client struct{}\n\n")
	body.WriteString("var Default Client\n\n")
	body.WriteString("type callArena struct {\n\tptrs []unsafe.Pointer\n}\n\n")
	body.WriteString("func (a *callArena) track(ptr unsafe.Pointer) {\n\tif ptr != nil {\n\t\ta.ptrs = append(a.ptrs, ptr)\n\t}\n}\n\n")
	body.WriteString("func (a *callArena) Free() {\n\tfor i := len(a.ptrs) - 1; i >= 0; i-- {\n\t\tC.free(a.ptrs[i])\n\t}\n\ta.ptrs = nil\n}\n\n")
	body.WriteString("func (a *callArena) String(value string) C.Go2ZigString {\n\tif len(value) == 0 {\n\t\treturn C.Go2ZigString{}\n\t}\n\tptr := C.CBytes([]byte(value))\n\ta.track(ptr)\n\treturn C.Go2ZigString{ptr: (*C.uint8_t)(ptr), len: C.size_t(len(value))}\n}\n\n")
	body.WriteString("func (a *callArena) Bytes(value []byte) C.Go2ZigBytes {\n\tif len(value) == 0 {\n\t\treturn C.Go2ZigBytes{}\n\t}\n\tptr := C.CBytes(value)\n\ta.track(ptr)\n\treturn C.Go2ZigBytes{ptr: (*C.uint8_t)(ptr), len: C.size_t(len(value))}\n}\n\n")
	body.WriteString("func ownString(value C.Go2ZigString) string {\n\tif value.ptr == nil {\n\t\treturn \"\"\n\t}\n\tdefer C.go2zig_free_buf(unsafe.Pointer(value.ptr), value.len)\n\tif value.len == 0 {\n\t\treturn \"\"\n\t}\n\treturn string(unsafe.Slice((*byte)(unsafe.Pointer(value.ptr)), int(value.len)))\n}\n\n")
	body.WriteString("func ownBytes(value C.Go2ZigBytes) []byte {\n\tif value.ptr == nil {\n\t\treturn nil\n\t}\n\tdefer C.go2zig_free_buf(unsafe.Pointer(value.ptr), value.len)\n\tif value.len == 0 {\n\t\treturn []byte{}\n\t}\n\treturn C.GoBytes(unsafe.Pointer(value.ptr), C.int(value.len))\n}\n\n")

	for _, item := range ordered {
		body.WriteString(renderGoStruct(item))
		body.WriteString(renderRefStruct(api, item))
		body.WriteString(renderOwnStruct(api, item))
	}

	for _, fn := range api.Funcs {
		body.WriteString(renderMethod(api, fn))
		body.WriteString("\n")
		body.WriteString(renderTopLevel(fn))
		body.WriteString("\n")
	}

	fmted, err := format.Source([]byte(body.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated go: %w", err)
	}
	return fmted, nil
}

func LibraryNameFromPath(path string) string {
	base := filepath.Base(path)
	ext := filepath.Ext(base)
	if ext != "" {
		base = strings.TrimSuffix(base, ext)
	}
	return base
}

func renderGoStruct(item *model.Struct) string {
	var b strings.Builder
	b.WriteString("type ")
	b.WriteString(item.Name)
	b.WriteString(" struct {\n")
	for _, field := range item.Fields {
		b.WriteString("\t")
		b.WriteString(names.Exported(field.Name))
		b.WriteString(" ")
		b.WriteString(goType(field.Type))
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")
	return b.String()
}

func renderRefStruct(api *model.API, item *model.Struct) string {
	var b strings.Builder
	b.WriteString("func ref")
	b.WriteString(item.Name)
	b.WriteString("(arena *callArena, value ")
	b.WriteString(item.Name)
	b.WriteString(") C.")
	b.WriteString(item.Name)
	b.WriteString(" {\n")
	b.WriteString("\treturn C.")
	b.WriteString(item.Name)
	b.WriteString("{\n")
	for _, field := range item.Fields {
		b.WriteString("\t\t")
		b.WriteString(field.Name)
		b.WriteString(": ")
		b.WriteString(refExpr(api, field.Type, "value."+names.Exported(field.Name)))
		b.WriteString(",\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	return b.String()
}

func renderOwnStruct(api *model.API, item *model.Struct) string {
	var b strings.Builder
	b.WriteString("func own")
	b.WriteString(item.Name)
	b.WriteString("(value C.")
	b.WriteString(item.Name)
	b.WriteString(") ")
	b.WriteString(item.Name)
	b.WriteString(" {\n")
	b.WriteString("\treturn ")
	b.WriteString(item.Name)
	b.WriteString("{\n")
	for _, field := range item.Fields {
		b.WriteString("\t\t")
		b.WriteString(names.Exported(field.Name))
		b.WriteString(": ")
		b.WriteString(ownExpr(api, field.Type, "value."+field.Name))
		b.WriteString(",\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	return b.String()
}

func renderMethod(api *model.API, fn *model.Function) string {
	goName := names.Exported(fn.Name)
	var b strings.Builder
	b.WriteString("func (Client) ")
	b.WriteString(goName)
	b.WriteString("(")
	for i, param := range fn.Params {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(goParamName(param.Name))
		b.WriteString(" ")
		b.WriteString(goType(param.Type))
	}
	b.WriteString(")")
	if fn.Return.Kind != model.TypeVoid {
		b.WriteString(" ")
		b.WriteString(goType(fn.Return))
	}
	b.WriteString(" {\n")
	b.WriteString("\tarena := &callArena{}\n")
	b.WriteString("\tdefer arena.Free()\n")
	if fn.Return.Kind != model.TypeVoid {
		b.WriteString("\tret := C.")
	} else {
		b.WriteString("\tC.")
	}
	b.WriteString(fn.Name)
	b.WriteString("(")
	for i, param := range fn.Params {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(refExpr(api, param.Type, goParamName(param.Name)))
	}
	b.WriteString(")\n")
	if fn.Return.Kind != model.TypeVoid {
		b.WriteString("\treturn ")
		b.WriteString(ownExpr(api, fn.Return, "ret"))
		b.WriteString("\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func renderTopLevel(fn *model.Function) string {
	goName := names.Exported(fn.Name)
	var b strings.Builder
	b.WriteString("func ")
	b.WriteString(goName)
	b.WriteString("(")
	for i, param := range fn.Params {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(goParamName(param.Name))
		b.WriteString(" ")
		b.WriteString(goType(param.Type))
	}
	b.WriteString(")")
	if fn.Return.Kind != model.TypeVoid {
		b.WriteString(" ")
		b.WriteString(goType(fn.Return))
	}
	b.WriteString(" {\n\t")
	if fn.Return.Kind != model.TypeVoid {
		b.WriteString("return ")
	}
	b.WriteString("Default.")
	b.WriteString(goName)
	b.WriteString("(")
	for i, param := range fn.Params {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(goParamName(param.Name))
	}
	b.WriteString(")\n}\n")
	return b.String()
}

func refExpr(api *model.API, t model.TypeRef, expr string) string {
	switch t.Kind {
	case model.TypePrimitive:
		return t.Primitive.CGo + "(" + expr + ")"
	case model.TypeString:
		return "arena.String(" + expr + ")"
	case model.TypeBytes:
		return "arena.Bytes(" + expr + ")"
	case model.TypeStruct:
		return "ref" + t.Name + "(arena, " + expr + ")"
	case model.TypeVoid:
		return ""
	default:
		return expr
	}
}

func ownExpr(api *model.API, t model.TypeRef, expr string) string {
	switch t.Kind {
	case model.TypePrimitive:
		return goType(t) + "(" + expr + ")"
	case model.TypeString:
		return "ownString(" + expr + ")"
	case model.TypeBytes:
		return "ownBytes(" + expr + ")"
	case model.TypeStruct:
		return "own" + t.Name + "(" + expr + ")"
	case model.TypeVoid:
		return ""
	default:
		return expr
	}
}

func goType(t model.TypeRef) string {
	switch t.Kind {
	case model.TypePrimitive:
		return t.Primitive.Go
	case model.TypeString:
		return "string"
	case model.TypeBytes:
		return "[]byte"
	case model.TypeStruct:
		return t.Name
	case model.TypeVoid:
		return ""
	default:
		return "any"
	}
}

func cType(t model.TypeRef) string {
	switch t.Kind {
	case model.TypePrimitive:
		return t.Primitive.C
	case model.TypeString:
		return "Go2ZigString"
	case model.TypeBytes:
		return "Go2ZigBytes"
	case model.TypeStruct:
		return t.Name
	case model.TypeVoid:
		return "void"
	default:
		return "void"
	}
}

func goParamName(name string) string {
	value := names.LowerCamel(name)
	if value == "" {
		return "arg"
	}
	switch value {
	case "type", "func", "map", "var", "range", "select", "defer", "go", "chan", "package", "import", "return":
		return value + "Value"
	default:
		return value
	}
}

func cgoLibraryName(name string) string {
	if strings.HasPrefix(name, "lib") {
		return strings.TrimPrefix(name, "lib")
	}
	return name
}
