package generator

import (
	"strings"
	"testing"

	"go2zig/internal/parser"
)

func TestRender(t *testing.T) {
	t.Parallel()

	api, err := parser.Parse(`
		pub const String = extern struct { ptr: [*]const u8, len: usize, };
		pub const Bytes = extern struct { ptr: [*]const u8, len: usize, };
		pub const ScoreList = extern struct { ptr: ?[*]const u16, len: usize, };
		pub const UserKindList = extern struct { ptr: ?[*]const UserKind, len: usize, };
		pub const DigestList = extern struct { ptr: ?[*]const [4]u8, len: usize, };
		pub const MetricList = extern struct { ptr: ?[*]const Metric, len: usize, };
		pub const UserKind = enum(u8) { guest, member, admin };
        pub const User = extern struct {
            id: u64,
            kind: UserKind,
            name: String,
            email: String,
            scores: [3]u16,
        };
		pub const Metric = extern struct {
			kind: UserKind,
			scores: [3]u16,
		};
        pub const LoginRequest = extern struct {
            user: User,
            password: String,
        };
		pub const LoginResponse = extern struct {
			ok: bool,
			message: String,
			token: Bytes,
			digest: [4]u8,
		};
		pub const LoginError = error{ InvalidPassword };
		pub extern fn health() bool;
		pub extern fn login(req: LoginRequest) LoginResponse;
		pub extern fn login_checked(req: LoginRequest) LoginError!LoginResponse;
		pub extern fn rename_user(user: User, next_name: String) User;
		pub extern fn promote_user(user: User, next_kind: UserKind, next_scores: [3]u16) User;
		pub extern fn digest_name(name: String) [4]u8;
		pub extern fn scale_scores(scores: ScoreList, factor: u16) ScoreList;
		pub extern fn mirror_kind_history(history: UserKindList) UserKindList;
		pub extern fn duplicate_digest(seed: String) DigestList;
		pub extern fn mirror_metrics(metrics: MetricList) MetricList;
	`)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}

	out, err := Render(api, Config{PackageName: "basic", LibraryName: "basic", APIModule: "api.zig", ImplModule: "lib.zig"})
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	content := string(out)
	checks := []string{
		"// Code generated by go2zig. DO NOT EDIT.",
		"//go:build amd64 && (windows || linux)",
		"package basic",
		"type Go2ZigClient struct",
		"type UserKind uint8",
		"type ScoreList []uint16",
		"type UserKindList []UserKind",
		"type DigestList [][4]uint8",
		"type MetricList []Metric",
		"UserKindAdmin",
		"func NewGo2ZigClient(path string) *Go2ZigClient",
		"func (c *Go2ZigClient) Login(req LoginRequest) LoginResponse",
		"func Login(req LoginRequest) LoginResponse",
		"func (c *Go2ZigClient) LoginChecked(req LoginRequest) (LoginResponse, error)",
		"func (c *Go2ZigClient) RenameUser(user User, nextName string) User",
		"func (c *Go2ZigClient) PromoteUser(user User, nextKind UserKind, nextScores [3]uint16) User",
		"func (c *Go2ZigClient) DigestName(name string) [4]uint8",
		"func (c *Go2ZigClient) ScaleScores(scores ScoreList, factor uint16) ScoreList",
		"func (c *Go2ZigClient) MirrorKindHistory(history UserKindList) UserKindList",
		"func (c *Go2ZigClient) DuplicateDigest(seed string) DigestList",
		"func (c *Go2ZigClient) MirrorMetrics(metrics MetricList) MetricList",
		"func _go2zigRefMetricList(value MetricList) _go2zigRefMetricListResult",
		"func _go2zigRefScoreList(value ScoreList) _go2zigRefScoreListResult",
		"func _go2zigRefArray_",
		"go2zig_call_login",
		"type Go2ZigError struct",
	}
	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Fatalf("Render() output missing %q\n%s", check, content)
		}
	}

	runtimeText := string(RenderZigRuntime(api, Config{APIModule: "api.zig"}))
	if !strings.Contains(runtimeText, "std.heap.smp_allocator") {
		t.Fatalf("RenderZigRuntime() should use smp_allocator\n%s", runtimeText)
	}
	bridgeText := string(RenderZigBridge(api, Config{APIModule: "api.zig", ImplModule: "lib.zig"}))
	if !strings.Contains(bridgeText, "pub export fn go2zig_call_login") {
		t.Fatalf("RenderZigBridge() missing exported login bridge\n%s", bridgeText)
	}
	if !strings.Contains(bridgeText, "catch |err|") {
		t.Fatalf("RenderZigBridge() missing error-union catch path\n%s", bridgeText)
	}
	if !strings.Contains(bridgeText, "pub export fn go2zig_free_buf") {
		t.Fatalf("RenderZigBridge() missing free bridge\n%s", bridgeText)
	}
}

func TestRenderVoidErrorFunction(t *testing.T) {
	t.Parallel()

	api, err := parser.Parse(`
        pub const FlushError = error{ Broken };
        pub extern fn flush() FlushError!void;
    `)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}

	out, err := Render(api, Config{PackageName: "basic", LibraryName: "basic", APIModule: "api.zig", ImplModule: "lib.zig"})
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}
	content := string(out)
	if !strings.Contains(content, "func (c *Go2ZigClient) Flush() error") {
		t.Fatalf("Render() missing void error signature\n%s", content)
	}
	if strings.Contains(content, "func (c *Go2ZigClient) Flush() (struct{}, error)") {
		t.Fatalf("Render() produced invalid void error signature\n%s", content)
	}

	bridgeText := string(RenderZigBridge(api, Config{APIModule: "api.zig", ImplModule: "lib.zig"}))
	if strings.Contains(bridgeText, "frame.out = result") {
		t.Fatalf("RenderZigBridge() should not assign out for void payload\n%s", bridgeText)
	}
	if !strings.Contains(bridgeText, "frame.err = rt.makeError(err)") {
		t.Fatalf("RenderZigBridge() missing error assignment\n%s", bridgeText)
	}
}

func TestDynamicLibraryFilename(t *testing.T) {
	t.Parallel()

	tests := []struct {
		goos string
		want string
	}{
		{goos: "windows", want: "basic.dll"},
		{goos: "linux", want: "libbasic.so"},
		{goos: "darwin", want: "libbasic.dylib"},
	}
	for _, tt := range tests {
		if got := DynamicLibraryFilename("basic", tt.goos); got != tt.want {
			t.Fatalf("DynamicLibraryFilename(%q) = %q, want %q", tt.goos, got, tt.want)
		}
	}
}
