package generator

import (
	"strings"
	"testing"

	"go2zig/internal/parser"
)

func TestRender(t *testing.T) {
	t.Parallel()

	api, err := parser.Parse(`
        pub const String = extern struct { ptr: [*]const u8, len: usize, };
        pub const Bytes = extern struct { ptr: [*]const u8, len: usize, };
        pub const User = extern struct {
            id: u64,
            name: String,
            email: String,
        };
        pub const LoginRequest = extern struct {
            user: User,
            password: String,
        };
        pub const LoginResponse = extern struct {
            ok: bool,
            message: String,
            token: Bytes,
        };
        pub extern fn health() bool;
        pub extern fn login(req: LoginRequest) LoginResponse;
        pub extern fn rename_user(user: User, next_name: String) User;
    `)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}

	out, err := Render(api, Config{PackageName: "basic", LibraryName: "basic"})
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	content := string(out)
	checks := []string{
		"// Code generated by go2zig. DO NOT EDIT.",
		"//go:build cgo",
		"package basic",
		"#cgo LDFLAGS: -L${SRCDIR} -lbasic",
		"type Client struct{}",
		"var Default Client",
		"type LoginResponse struct {",
		"OK      bool",
		"func (Client) Login(req LoginRequest) LoginResponse",
		"func Login(req LoginRequest) LoginResponse",
		"func (Client) RenameUser(user User, nextName string) User",
		"func ownString(value C.Go2ZigString) string",
	}
	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Fatalf("Render() output missing %q\n%s", check, content)
		}
	}
}
