// Code generated by go2zig. DO NOT EDIT.
//go:build cgo

package main

/*
#cgo LDFLAGS: -L${SRCDIR} -lbasic
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>

typedef struct Go2ZigString {
	const uint8_t *ptr;
	size_t len;
} Go2ZigString;

typedef struct Go2ZigBytes {
	const uint8_t *ptr;
	size_t len;
} Go2ZigBytes;

typedef struct User {
	uint64_t id;
	Go2ZigString name;
	Go2ZigString email;
} User;

typedef struct LoginRequest {
	User user;
	Go2ZigString password;
} LoginRequest;

typedef struct LoginResponse {
	bool ok;
	Go2ZigString message;
	Go2ZigBytes token;
} LoginResponse;

extern void go2zig_free_buf(void *ptr, size_t len);
extern bool health(void);
extern LoginResponse login(LoginRequest req);
extern User rename_user(User user, Go2ZigString next_name);
*/
import "C"

import (
	"unsafe"
)

type Client struct{}

var Default Client

type callArena struct {
	ptrs []unsafe.Pointer
}

func (a *callArena) track(ptr unsafe.Pointer) {
	if ptr != nil {
		a.ptrs = append(a.ptrs, ptr)
	}
}

func (a *callArena) Free() {
	for i := len(a.ptrs) - 1; i >= 0; i-- {
		C.free(a.ptrs[i])
	}
	a.ptrs = nil
}

func (a *callArena) String(value string) C.Go2ZigString {
	if len(value) == 0 {
		return C.Go2ZigString{}
	}
	ptr := C.CBytes([]byte(value))
	a.track(ptr)
	return C.Go2ZigString{ptr: ptr, len: C.size_t(len(value))}
}

func (a *callArena) Bytes(value []byte) C.Go2ZigBytes {
	if len(value) == 0 {
		return C.Go2ZigBytes{}
	}
	ptr := C.CBytes(value)
	a.track(ptr)
	return C.Go2ZigBytes{ptr: ptr, len: C.size_t(len(value))}
}

func ownString(value C.Go2ZigString) string {
	if value.ptr == nil {
		return ""
	}
	defer C.go2zig_free_buf(unsafe.Pointer(value.ptr), value.len)
	if value.len == 0 {
		return ""
	}
	return string(unsafe.Slice((*byte)(unsafe.Pointer(value.ptr)), int(value.len)))
}

func ownBytes(value C.Go2ZigBytes) []byte {
	if value.ptr == nil {
		return nil
	}
	defer C.go2zig_free_buf(unsafe.Pointer(value.ptr), value.len)
	if value.len == 0 {
		return []byte{}
	}
	return C.GoBytes(unsafe.Pointer(value.ptr), C.int(value.len))
}

type User struct {
	ID    uint64
	Name  string
	Email string
}

func refUser(arena *callArena, value User) C.User {
	return C.User{
		id:    C.uint64_t(value.ID),
		name:  arena.String(value.Name),
		email: arena.String(value.Email),
	}
}

func ownUser(value C.User) User {
	return User{
		ID:    uint64(value.id),
		Name:  ownString(value.name),
		Email: ownString(value.email),
	}
}

type LoginRequest struct {
	User     User
	Password string
}

func refLoginRequest(arena *callArena, value LoginRequest) C.LoginRequest {
	return C.LoginRequest{
		user:     refUser(arena, value.User),
		password: arena.String(value.Password),
	}
}

func ownLoginRequest(value C.LoginRequest) LoginRequest {
	return LoginRequest{
		User:     ownUser(value.user),
		Password: ownString(value.password),
	}
}

type LoginResponse struct {
	OK      bool
	Message string
	Token   []byte
}

func refLoginResponse(arena *callArena, value LoginResponse) C.LoginResponse {
	return C.LoginResponse{
		ok:      C.bool(value.OK),
		message: arena.String(value.Message),
		token:   arena.Bytes(value.Token),
	}
}

func ownLoginResponse(value C.LoginResponse) LoginResponse {
	return LoginResponse{
		OK:      bool(value.ok),
		Message: ownString(value.message),
		Token:   ownBytes(value.token),
	}
}

func (Client) Health() bool {
	arena := &callArena{}
	defer arena.Free()
	ret := C.health()
	return bool(ret)
}

func Health() bool {
	return Default.Health()
}

func (Client) Login(req LoginRequest) LoginResponse {
	arena := &callArena{}
	defer arena.Free()
	ret := C.login(refLoginRequest(arena, req))
	return ownLoginResponse(ret)
}

func Login(req LoginRequest) LoginResponse {
	return Default.Login(req)
}

func (Client) RenameUser(user User, nextName string) User {
	arena := &callArena{}
	defer arena.Free()
	ret := C.rename_user(refUser(arena, user), arena.String(nextName))
	return ownUser(ret)
}

func RenameUser(user User, nextName string) User {
	return Default.RenameUser(user, nextName)
}
