// Code generated by go2zig. DO NOT EDIT.
//go:build amd64 && (windows || linux)

package main

import (
	"fmt"
	"path/filepath"
	"runtime"
	"sync"
	"unsafe"

	"go2zig/asmcall"
	"go2zig/dynlib"
)

type Go2ZigClient struct {
	rt *_go2zigRuntime
}

func NewGo2ZigClient(path string) *Go2ZigClient {
	return &Go2ZigClient{rt: &_go2zigRuntime{path: path}}
}

var Default = NewGo2ZigClient("")

type _go2zigRuntime struct {
	path             string
	once             sync.Once
	lib              *dynlib.Library
	freeBuf          uintptr
	procHealth       uintptr
	procLogin        uintptr
	procLoginChecked uintptr
	procRenameUser   uintptr
	procPromoteUser  uintptr
	procDigestName   uintptr
	err              error
}

func (rt *_go2zigRuntime) Load() error {
	rt.once.Do(func() {
		path := rt.path
		if path == "" {
			path = _go2zigDefaultLibraryPath()
		}
		lib, err := dynlib.Load(path)
		if err != nil {
			rt.err = fmt.Errorf("go2zig: load %s: %w", path, err)
			return
		}
		rt.lib = lib
		if rt.freeBuf, err = lib.Lookup("go2zig_free_buf"); err != nil {
			rt.err = fmt.Errorf("go2zig: lookup go2zig_free_buf: %w", err)
			return
		}
		if rt.procHealth, err = lib.Lookup("go2zig_call_health"); err != nil {
			rt.err = fmt.Errorf("go2zig: lookup go2zig_call_health: %w", err)
			return
		}
		if rt.procLogin, err = lib.Lookup("go2zig_call_login"); err != nil {
			rt.err = fmt.Errorf("go2zig: lookup go2zig_call_login: %w", err)
			return
		}
		if rt.procLoginChecked, err = lib.Lookup("go2zig_call_login_checked"); err != nil {
			rt.err = fmt.Errorf("go2zig: lookup go2zig_call_login_checked: %w", err)
			return
		}
		if rt.procRenameUser, err = lib.Lookup("go2zig_call_rename_user"); err != nil {
			rt.err = fmt.Errorf("go2zig: lookup go2zig_call_rename_user: %w", err)
			return
		}
		if rt.procPromoteUser, err = lib.Lookup("go2zig_call_promote_user"); err != nil {
			rt.err = fmt.Errorf("go2zig: lookup go2zig_call_promote_user: %w", err)
			return
		}
		if rt.procDigestName, err = lib.Lookup("go2zig_call_digest_name"); err != nil {
			rt.err = fmt.Errorf("go2zig: lookup go2zig_call_digest_name: %w", err)
			return
		}
	})
	return rt.err
}

func (rt *_go2zigRuntime) free(ptr unsafe.Pointer, len uintptr) {
	if ptr == nil {
		return
	}
	if err := rt.Load(); err != nil {
		panic(err)
	}
	asmcall.CallFuncG0P2(unsafe.Pointer(rt.freeBuf), ptr, unsafe.Pointer(len))
}

func (rt *_go2zigRuntime) call(proc uintptr, frame unsafe.Pointer) {
	if err := rt.Load(); err != nil {
		panic(err)
	}
	asmcall.CallFuncG0P1(unsafe.Pointer(proc), frame)
}

func _go2zigDefaultLibraryPath() string {
	_, file, _, ok := runtime.Caller(0)
	name := _go2zigDynamicLibraryName()
	if !ok {
		return name
	}
	return filepath.Join(filepath.Dir(file), name)
}

func (c *Go2ZigClient) Load() error {
	return c.rt.Load()
}

func _go2zigDynamicLibraryName() string {
	switch runtime.GOOS {
	case "windows":
		return "basic.dll"
	case "darwin":
		return "libbasic.dylib"
	default:
		return "libbasic.so"
	}
}

type _go2zigString struct {
	Ptr unsafe.Pointer
	Len uintptr
}

type _go2zigBytes struct {
	Ptr unsafe.Pointer
	Len uintptr
}

type _go2zigError struct {
	Code uint32
	Text _go2zigString
}

func _go2zigBool(v bool) uint8 {
	if v {
		return 1
	}
	return 0
}

func _go2zigFromBool(v uint8) bool {
	return v != 0
}

func _go2zigRefString(value string) _go2zigString {
	if len(value) == 0 {
		return _go2zigString{}
	}
	return _go2zigString{Ptr: unsafe.Pointer(unsafe.StringData(value)), Len: uintptr(len(value))}
}

func _go2zigRefBytes(value []byte) _go2zigBytes {
	if len(value) == 0 {
		return _go2zigBytes{}
	}
	return _go2zigBytes{Ptr: unsafe.Pointer(unsafe.SliceData(value)), Len: uintptr(len(value))}
}

func _go2zigOwnString(rt *_go2zigRuntime, value _go2zigString) string {
	if value.Ptr == nil || value.Len == 0 {
		return ""
	}
	bytes := unsafe.Slice((*byte)(value.Ptr), int(value.Len))
	ret := string(bytes)
	rt.free(value.Ptr, value.Len)
	return ret
}

func _go2zigOwnBytes(rt *_go2zigRuntime, value _go2zigBytes) []byte {
	if value.Ptr == nil || value.Len == 0 {
		return nil
	}
	ret := append([]byte(nil), unsafe.Slice((*byte)(value.Ptr), int(value.Len))...)
	rt.free(value.Ptr, value.Len)
	return ret
}

func _go2zigOwnError(rt *_go2zigRuntime, value _go2zigError) error {
	if value.Code == 0 {
		return nil
	}
	return &Go2ZigError{Code: value.Code, Message: _go2zigOwnString(rt, value.Text)}
}

type Go2ZigError struct {
	Code    uint32
	Message string
}

func (e *Go2ZigError) Error() string {
	if e == nil {
		return "<nil>"
	}
	if e.Message != "" {
		return e.Message
	}
	return fmt.Sprintf("zig error code %d", e.Code)
}

type UserKind uint8

const (
	UserKindGuest  UserKind = UserKind(0)
	UserKindMember UserKind = UserKind(1)
	UserKindAdmin  UserKind = UserKind(2)
)

func _go2zigRefArray_array_3_1_u16(value [3]uint16) [3]uint16 {
	var out [3]uint16
	for i := range value {
		out[i] = uint16(value[i])
	}
	return out
}

func _go2zigOwnArray_array_3_1_u16(rt *_go2zigRuntime, value [3]uint16) [3]uint16 {
	var out [3]uint16
	for i := range value {
		out[i] = uint16(value[i])
	}
	return out
}

func _go2zigRefArray_array_4_1_u8(value [4]uint8) [4]uint8 {
	var out [4]uint8
	for i := range value {
		out[i] = uint8(value[i])
	}
	return out
}

func _go2zigOwnArray_array_4_1_u8(rt *_go2zigRuntime, value [4]uint8) [4]uint8 {
	var out [4]uint8
	for i := range value {
		out[i] = uint8(value[i])
	}
	return out
}

type User struct {
	ID     uint64
	Kind   UserKind
	Name   string
	Email  string
	Scores [3]uint16
}

type _go2zigUser struct {
	id     uint64
	kind   uint8
	name   _go2zigString
	email  _go2zigString
	scores [3]uint16
}

func _go2zigRefUser(value User) _go2zigUser {
	return _go2zigUser{
		id:     uint64(value.ID),
		kind:   uint8(value.Kind),
		name:   _go2zigRefString(value.Name),
		email:  _go2zigRefString(value.Email),
		scores: _go2zigRefArray_array_3_1_u16(value.Scores),
	}
}

func _go2zigOwnUser(rt *_go2zigRuntime, value _go2zigUser) User {
	return User{
		ID:     uint64(value.id),
		Kind:   UserKind(value.kind),
		Name:   _go2zigOwnString(rt, value.name),
		Email:  _go2zigOwnString(rt, value.email),
		Scores: _go2zigOwnArray_array_3_1_u16(rt, value.scores),
	}
}

type LoginRequest struct {
	User     User
	Password string
}

type _go2zigLoginRequest struct {
	user     _go2zigUser
	password _go2zigString
}

func _go2zigRefLoginRequest(value LoginRequest) _go2zigLoginRequest {
	return _go2zigLoginRequest{
		user:     _go2zigRefUser(value.User),
		password: _go2zigRefString(value.Password),
	}
}

func _go2zigOwnLoginRequest(rt *_go2zigRuntime, value _go2zigLoginRequest) LoginRequest {
	return LoginRequest{
		User:     _go2zigOwnUser(rt, value.user),
		Password: _go2zigOwnString(rt, value.password),
	}
}

type LoginResponse struct {
	OK      bool
	Message string
	Token   []byte
	Digest  [4]uint8
}

type _go2zigLoginResponse struct {
	ok      uint8
	message _go2zigString
	token   _go2zigBytes
	digest  [4]uint8
}

func _go2zigRefLoginResponse(value LoginResponse) _go2zigLoginResponse {
	return _go2zigLoginResponse{
		ok:      _go2zigBool(value.OK),
		message: _go2zigRefString(value.Message),
		token:   _go2zigRefBytes(value.Token),
		digest:  _go2zigRefArray_array_4_1_u8(value.Digest),
	}
}

func _go2zigOwnLoginResponse(rt *_go2zigRuntime, value _go2zigLoginResponse) LoginResponse {
	return LoginResponse{
		OK:      _go2zigFromBool(value.ok),
		Message: _go2zigOwnString(rt, value.message),
		Token:   _go2zigOwnBytes(rt, value.token),
		Digest:  _go2zigOwnArray_array_4_1_u8(rt, value.digest),
	}
}

type _go2zigCallHealth struct {
	out uint8
}

type _go2zigCallLogin struct {
	req _go2zigLoginRequest
	out _go2zigLoginResponse
}

type _go2zigCallLoginChecked struct {
	req _go2zigLoginRequest
	out _go2zigLoginResponse
	err _go2zigError
}

type _go2zigCallRenameUser struct {
	user      _go2zigUser
	next_name _go2zigString
	out       _go2zigUser
}

type _go2zigCallPromoteUser struct {
	user        _go2zigUser
	next_kind   uint8
	next_scores [3]uint16
	out         _go2zigUser
}

type _go2zigCallDigestName struct {
	name _go2zigString
	out  [4]uint8
}

func (c *Go2ZigClient) Health() bool {
	var frame _go2zigCallHealth
	c.rt.call(c.rt.procHealth, unsafe.Pointer(&frame))
	return _go2zigFromBool(frame.out)
}

func Health() bool {
	return Default.Health()
}

func (c *Go2ZigClient) Login(req LoginRequest) LoginResponse {
	var frame _go2zigCallLogin
	frame.req = _go2zigRefLoginRequest(req)
	c.rt.call(c.rt.procLogin, unsafe.Pointer(&frame))
	runtime.KeepAlive(req)
	return _go2zigOwnLoginResponse(c.rt, frame.out)
}

func Login(req LoginRequest) LoginResponse {
	return Default.Login(req)
}

func (c *Go2ZigClient) LoginChecked(req LoginRequest) (LoginResponse, error) {
	var frame _go2zigCallLoginChecked
	frame.req = _go2zigRefLoginRequest(req)
	c.rt.call(c.rt.procLoginChecked, unsafe.Pointer(&frame))
	runtime.KeepAlive(req)
	if err := _go2zigOwnError(c.rt, frame.err); err != nil {
		var zero LoginResponse
		return zero, err
	}
	return _go2zigOwnLoginResponse(c.rt, frame.out), nil
}

func LoginChecked(req LoginRequest) (LoginResponse, error) {
	return Default.LoginChecked(req)
}

func (c *Go2ZigClient) RenameUser(user User, nextName string) User {
	var frame _go2zigCallRenameUser
	frame.user = _go2zigRefUser(user)
	frame.next_name = _go2zigRefString(nextName)
	c.rt.call(c.rt.procRenameUser, unsafe.Pointer(&frame))
	runtime.KeepAlive(user)
	runtime.KeepAlive(nextName)
	return _go2zigOwnUser(c.rt, frame.out)
}

func RenameUser(user User, nextName string) User {
	return Default.RenameUser(user, nextName)
}

func (c *Go2ZigClient) PromoteUser(user User, nextKind UserKind, nextScores [3]uint16) User {
	var frame _go2zigCallPromoteUser
	frame.user = _go2zigRefUser(user)
	frame.next_kind = uint8(nextKind)
	frame.next_scores = _go2zigRefArray_array_3_1_u16(nextScores)
	c.rt.call(c.rt.procPromoteUser, unsafe.Pointer(&frame))
	runtime.KeepAlive(user)
	runtime.KeepAlive(nextKind)
	runtime.KeepAlive(nextScores)
	return _go2zigOwnUser(c.rt, frame.out)
}

func PromoteUser(user User, nextKind UserKind, nextScores [3]uint16) User {
	return Default.PromoteUser(user, nextKind, nextScores)
}

func (c *Go2ZigClient) DigestName(name string) [4]uint8 {
	var frame _go2zigCallDigestName
	frame.name = _go2zigRefString(name)
	c.rt.call(c.rt.procDigestName, unsafe.Pointer(&frame))
	runtime.KeepAlive(name)
	return _go2zigOwnArray_array_4_1_u8(c.rt, frame.out)
}

func DigestName(name string) [4]uint8 {
	return Default.DigestName(name)
}
