// Code generated by go2zig. DO NOT EDIT.
const std = @import("std");
const api = @import("api.zig");

pub const ErrorInfo = extern struct {
    code: u32,
    text: api.String,
};

pub inline fn asSlice(value: api.String) []const u8 {
    if (value.len == 0) return "";
    return value.ptr[0..value.len];
}

pub inline fn asBytes(value: api.Bytes) []const u8 {
    if (value.len == 0) return &.{};
    return value.ptr[0..value.len];
}

pub fn ownString(value: []const u8) api.String {
    if (value.len == 0) return .{ .ptr = undefined, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(u8, value.len) catch @panic("go2zig: alloc string failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub fn ownBytes(value: []const u8) api.Bytes {
    if (value.len == 0) return .{ .ptr = undefined, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(u8, value.len) catch @panic("go2zig: alloc bytes failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub fn freeBuf(ptr: ?*anyopaque, len: usize) void {
    if (len == 0 or ptr == null) return;
    const buf = @as([*]u8, @ptrCast(ptr.?))[0..len];
    std.heap.smp_allocator.free(buf);
}

pub fn okError() ErrorInfo {
    return .{ .code = 0, .text = .{ .ptr = undefined, .len = 0 } };
}

pub fn makeError(err: anyerror) ErrorInfo {
    return .{
        .code = @intFromError(err),
        .text = ownString(@errorName(err)),
    };
}

pub inline fn asScoreList(value: api.ScoreList) []const u16 {
    if (value.ptr == null or value.len == 0) return &.{};
    return value.ptr.?[0..value.len];
}

pub fn ownScoreList(value: []const u16) api.ScoreList {
    if (value.len == 0) return .{ .ptr = null, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(u16, value.len) catch @panic("go2zig: alloc slice failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}
