// Code generated by go2zig. DO NOT EDIT.
const api = @import("api.zig");
const impl = @import("lib.zig");
const rt = @import("go2zig_runtime.zig");

pub export fn go2zig_free_buf(ptr: ?*anyopaque, len: usize) void {
    rt.freeBuf(ptr, len);
}

pub const Go2ZigCallHealth = extern struct {
    out: bool,
};

pub export fn go2zig_call_health(frame: *Go2ZigCallHealth) void {
    frame.out = impl.health();
}

pub const Go2ZigCallLogin = extern struct {
    req: api.LoginRequest,
    out: api.LoginResponse,
};

pub export fn go2zig_call_login(frame: *Go2ZigCallLogin) void {
    frame.out = impl.login(frame.req);
}

pub const Go2ZigCallRenameUser = extern struct {
    user: api.User,
    next_name: api.String,
    out: api.User,
};

pub export fn go2zig_call_rename_user(frame: *Go2ZigCallRenameUser) void {
    frame.out = impl.rename_user(frame.user, frame.next_name);
}

