// Code generated by go2zig. DO NOT EDIT.
const std = @import("std");
const api = @import("api.zig");

pub const ErrorInfo = extern struct {
    code: u32,
    text: api.String,
};

pub inline fn asSlice(value: api.String) []const u8 {
    if (value.len == 0) return "";
    return value.ptr[0..value.len];
}

pub inline fn asBytes(value: api.Bytes) []const u8 {
    if (value.len == 0) return &.{};
    return value.ptr[0..value.len];
}

pub fn ownString(value: []const u8) api.String {
    if (value.len == 0) return .{ .ptr = undefined, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(u8, value.len) catch @panic("go2zig: alloc string failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub fn ownBytes(value: []const u8) api.Bytes {
    if (value.len == 0) return .{ .ptr = undefined, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(u8, value.len) catch @panic("go2zig: alloc bytes failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub fn freeBuf(ptr: ?*anyopaque, len: usize) void {
    if (len == 0 or ptr == null) return;
    const buf = @as([*]u8, @ptrCast(ptr.?))[0..len];
    std.heap.smp_allocator.free(buf);
}

pub fn okError() ErrorInfo {
    return .{ .code = 0, .text = .{ .ptr = undefined, .len = 0 } };
}

pub fn makeError(err: anyerror) ErrorInfo {
    return .{
        .code = @intFromError(err),
        .text = ownString(@errorName(err)),
    };
}

pub inline fn asScoreList(value: api.ScoreList) []const u16 {
    if (value.ptr == null or value.len == 0) return &.{};
    return value.ptr.?[0..value.len];
}

pub fn ownScoreList(value: []const u16) api.ScoreList {
    if (value.len == 0) return .{ .ptr = null, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(u16, value.len) catch @panic("go2zig: alloc slice failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub inline fn asUserKindList(value: api.UserKindList) []const api.UserKind {
    if (value.ptr == null or value.len == 0) return &.{};
    return value.ptr.?[0..value.len];
}

pub fn ownUserKindList(value: []const api.UserKind) api.UserKindList {
    if (value.len == 0) return .{ .ptr = null, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(api.UserKind, value.len) catch @panic("go2zig: alloc slice failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub inline fn asDigestList(value: api.DigestList) []const api.Digest {
    if (value.ptr == null or value.len == 0) return &.{};
    return value.ptr.?[0..value.len];
}

pub fn ownDigestList(value: []const api.Digest) api.DigestList {
    if (value.len == 0) return .{ .ptr = null, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(api.Digest, value.len) catch @panic("go2zig: alloc slice failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub inline fn asMetricList(value: api.MetricList) []const api.Metric {
    if (value.ptr == null or value.len == 0) return &.{};
    return value.ptr.?[0..value.len];
}

pub fn ownMetricList(value: []const api.Metric) api.MetricList {
    if (value.len == 0) return .{ .ptr = null, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(api.Metric, value.len) catch @panic("go2zig: alloc slice failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub inline fn asUserList(value: api.UserList) []const api.User {
    if (value.ptr == null or value.len == 0) return &.{};
    return value.ptr.?[0..value.len];
}

pub fn ownUserList(value: []const api.User) api.UserList {
    if (value.len == 0) return .{ .ptr = null, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(api.User, value.len) catch @panic("go2zig: alloc slice failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub inline fn asBucketList(value: api.BucketList) []const api.Bucket {
    if (value.ptr == null or value.len == 0) return &.{};
    return value.ptr.?[0..value.len];
}

pub fn ownBucketList(value: []const api.Bucket) api.BucketList {
    if (value.len == 0) return .{ .ptr = null, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(api.Bucket, value.len) catch @panic("go2zig: alloc slice failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub const Optional_optional_1_u32 = extern struct {
    is_set: u8,
    value: u32,
};

pub inline fn toOptional_optional_1_u32(value: Optional_optional_1_u32) ?u32 {
    if (value.is_set == 0) return null;
    return value.value;
}

pub inline fn fromOptional_optional_1_u32(value: ?u32) Optional_optional_1_u32 {
    if (value) |item| {
        return .{ .is_set = 1, .value = item };
    }
    return .{ .is_set = 0, .value = undefined };
}

pub const Optional_optional_5_UserKind = extern struct {
    is_set: u8,
    value: api.UserKind,
};

pub inline fn toOptional_optional_5_UserKind(value: Optional_optional_5_UserKind) ?api.UserKind {
    if (value.is_set == 0) return null;
    return value.value;
}

pub inline fn fromOptional_optional_5_UserKind(value: ?api.UserKind) Optional_optional_5_UserKind {
    if (value) |item| {
        return .{ .is_set = 1, .value = item };
    }
    return .{ .is_set = 0, .value = undefined };
}

pub const Optional_optional_arrayalias_Digest = extern struct {
    is_set: u8,
    value: api.Digest,
};

pub inline fn toOptional_optional_arrayalias_Digest(value: Optional_optional_arrayalias_Digest) ?api.Digest {
    if (value.is_set == 0) return null;
    return value.value;
}

pub inline fn fromOptional_optional_arrayalias_Digest(value: ?api.Digest) Optional_optional_arrayalias_Digest {
    if (value) |item| {
        return .{ .is_set = 1, .value = item };
    }
    return .{ .is_set = 0, .value = undefined };
}
