// Code generated by go2zig. DO NOT EDIT.
const api = @import("api.zig");
const impl = @import("lib.zig");
const rt = @import("go2zig_runtime.zig");

pub export fn go2zig_free_buf(ptr: ?*anyopaque, len: usize) void {
    rt.freeBuf(ptr, len);
}

pub const Go2ZigCallHealth = extern struct {
    out: bool,
};

pub export fn go2zig_call_health(frame: *Go2ZigCallHealth) void {
    frame.out = impl.health();
}

pub const Go2ZigCallLogin = extern struct {
    req: api.LoginRequest,
    out: api.LoginResponse,
};

pub export fn go2zig_call_login(frame: *Go2ZigCallLogin) void {
    frame.out = impl.login(frame.req);
}

pub const Go2ZigCallLoginChecked = extern struct {
    req: api.LoginRequest,
    out: api.LoginResponse,
    err: rt.ErrorInfo,
};

pub export fn go2zig_call_login_checked(frame: *Go2ZigCallLoginChecked) void {
    frame.err = rt.okError();
    const result = impl.login_checked(frame.req) catch |err| {
        frame.err = rt.makeError(err);
        return;
    };
    frame.out = result;
}

pub const Go2ZigCallRenameUser = extern struct {
    user: api.User,
    next_name: api.String,
    out: api.User,
};

pub export fn go2zig_call_rename_user(frame: *Go2ZigCallRenameUser) void {
    frame.out = impl.rename_user(frame.user, frame.next_name);
}

pub const Go2ZigCallPromoteUser = extern struct {
    user: api.User,
    next_kind: api.UserKind,
    next_scores: [3]u16,
    out: api.User,
};

pub export fn go2zig_call_promote_user(frame: *Go2ZigCallPromoteUser) void {
    frame.out = impl.promote_user(frame.user, frame.next_kind, frame.next_scores);
}

pub const Go2ZigCallDigestName = extern struct {
    name: api.String,
    out: [4]u8,
};

pub export fn go2zig_call_digest_name(frame: *Go2ZigCallDigestName) void {
    frame.out = impl.digest_name(frame.name);
}

pub const Go2ZigCallScaleScores = extern struct {
    scores: api.ScoreList,
    factor: u16,
    out: api.ScoreList,
};

pub export fn go2zig_call_scale_scores(frame: *Go2ZigCallScaleScores) void {
    frame.out = impl.scale_scores(frame.scores, frame.factor);
}

pub const Go2ZigCallMirrorKindHistory = extern struct {
    history: api.UserKindList,
    out: api.UserKindList,
};

pub export fn go2zig_call_mirror_kind_history(frame: *Go2ZigCallMirrorKindHistory) void {
    frame.out = impl.mirror_kind_history(frame.history);
}

pub const Go2ZigCallDuplicateDigest = extern struct {
    seed: api.String,
    out: api.DigestList,
};

pub export fn go2zig_call_duplicate_digest(frame: *Go2ZigCallDuplicateDigest) void {
    frame.out = impl.duplicate_digest(frame.seed);
}

pub const Go2ZigCallMirrorMetrics = extern struct {
    metrics: api.MetricList,
    out: api.MetricList,
};

pub export fn go2zig_call_mirror_metrics(frame: *Go2ZigCallMirrorMetrics) void {
    frame.out = impl.mirror_metrics(frame.metrics);
}

pub const Go2ZigCallMirrorUsers = extern struct {
    users: api.UserList,
    out: api.UserList,
};

pub export fn go2zig_call_mirror_users(frame: *Go2ZigCallMirrorUsers) void {
    frame.out = impl.mirror_users(frame.users);
}

