// Code generated by go2zig. DO NOT EDIT.
const std = @import("std");
const api = @import("api.zig");

pub inline fn asSlice(value: api.String) []const u8 {
    if (value.len == 0) return "";
    return value.ptr[0..value.len];
}

pub inline fn asBytes(value: api.Bytes) []const u8 {
    if (value.len == 0) return &.{};
    return value.ptr[0..value.len];
}

pub fn ownString(value: []const u8) api.String {
    if (value.len == 0) return .{ .ptr = undefined, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(u8, value.len) catch @panic("go2zig: alloc string failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub fn ownBytes(value: []const u8) api.Bytes {
    if (value.len == 0) return .{ .ptr = undefined, .len = 0 };
    const buf = std.heap.smp_allocator.alloc(u8, value.len) catch @panic("go2zig: alloc bytes failed");
    @memcpy(buf, value);
    return .{ .ptr = buf.ptr, .len = buf.len };
}

pub fn freeBuf(ptr: ?*anyopaque, len: usize) void {
    if (len == 0 or ptr == null) return;
    const buf = @as([*]u8, @ptrCast(ptr.?))[0..len];
    std.heap.smp_allocator.free(buf);
}
